name: Build js

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Yarn install dependencies for build
        run: yarn install
      - name: Yarn build
        run: yarn build
      - name: Yarn install production dependencies
        run: |
          rm -rf node_modules
          yarn install --production=true --frozen-lockfile
      - name: Archive build artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: build.zip
          path: |
            build
            node_modules
            package.json
