name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Yarn install
        run: yarn install
      - name: Yarn build
        run: yarn build
      - name: Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            build
